// Source data — transcribed verbatim from "Assignment 2 DataPack: Internal Service Agent (IT Support)".
// The agent may ONLY ground answers in these records. Nothing here is invented.
window.DATA = {
  company: "Veridian Corp",
  week: { start: "2026-09-21", end: "2026-09-25" },
  securityEmail: "security@veridian-corp.example",

  kb: {
    "KB-01": { title: "Password Reset", owner: "IT",
      text: "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required." },
    "KB-02": { title: "VPN Access", owner: "IT",
      text: "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee." },
    "KB-03": { title: "Laptop Replacement", owner: "IT",
      text: "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement." },
    "KB-04": { title: "Software Installation Requests", owner: "IT / IT Security",
      text: "Standard software (listed in the approved catalog) can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days." },
    "KB-05": { title: "Printer Troubleshooting", owner: "IT",
      text: "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag." },
    "KB-06": { title: "Email Mailbox Quota", owner: "IT",
      text: "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB." },
    "KB-07": { title: "Guest Wi-Fi Access", owner: "Front desk (self-service)",
      text: "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required." },
    "KB-08": { title: "Expense Software Access", owner: "Finance",
      text: "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists." },
    "KB-09": { title: "Security Incident Reporting", owner: "IT Security",
      text: "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees." },
    "KB-10": { title: "Work-From-Home Equipment", owner: "Manager + Finance (IT ships)",
      text: "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved." },
    "AMP": { title: "Asset Management Policy (Extract) — Finance & Assets, updated Q2 2026", owner: "Finance & Assets",
      text: "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval." }
  },

  requests: [
    { id: "REQ-01", name: "Aditi Sharma",   email: "aditi.sharma@veridian-corp.example",   date: "2026-09-21", text: "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now.", status: "Not started" },
    { id: "REQ-02", name: "Vikram Chawla",  email: "vikram.chawla@veridian-corp.example",  date: "2026-09-21", text: "Can I get Wi-Fi access for a guest visiting our office tomorrow?", status: "Not started" },
    { id: "REQ-03", name: "Karan Mehta",    email: "karan.mehta@veridian-corp.example",    date: "2026-09-21", text: "I'm locked out of my account, tried my password 6 times.", status: "In progress — reset queued" },
    { id: "REQ-04", name: "Ritu Bhatia",    email: "ritu.bhatia@veridian-corp.example",    date: "2026-09-22", text: "Need approval to install a data-analysis tool that's not in the software catalog.", status: "Waiting on Security review" },
    { id: "REQ-05", name: "Sanjay Oberoi",  email: "sanjay.oberoi@veridian-corp.example",  date: "2026-09-22", text: "My VPN stopped working this morning, says credentials expired.", status: "Not started" },
    { id: "REQ-06", name: "Meera Iyer",     email: "meera.iyer@veridian-corp.example",     date: "2026-09-22", text: "Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam.", status: "Investigating — technician assigned" },
    { id: "REQ-07", name: "Farhan Ali",     email: "farhan.ali@veridian-corp.example",     date: "2026-09-23", text: "I've started working from home 4 days a week, how do I get a monitor?", status: "Not started" },
    { id: "REQ-08", name: "Ananya Reddy",   email: "ananya.reddy@veridian-corp.example",   date: "2026-09-23", text: "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.", status: "Escalated to Security (auto-flagged)" },
    { id: "REQ-09", name: "Rohit Desai",    email: "rohit.desai@veridian-corp.example",    date: "2026-09-23", text: "My mailbox is full and I can't send emails.", status: "Not started" },
    { id: "REQ-10", name: "Kavya Pillai",   email: "kavya.pillai@veridian-corp.example",   date: "2026-09-23", text: "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.", status: "Not started" },
    { id: "REQ-11", name: "Nikhil Bansal",  email: "nikhil.bansal@veridian-corp.example",  date: "2026-09-24", text: "New contractor joining my team next week, they'll need VPN access.", status: "Not started" },
    { id: "REQ-12", name: "Sneha Kulkarni", email: "sneha.kulkarni@veridian-corp.example", date: "2026-09-24", text: "I can't log into the expense tool, keeps saying invalid credentials.", status: "Waiting on employee response (asked for a screenshot, no reply yet)" },
    { id: "REQ-13", name: "Aman Gupta",     email: "aman.gupta@veridian-corp.example",     date: "2026-09-24", text: "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.", status: "Not started" },
    { id: "REQ-14", name: "Tanya Chopra",   email: "tanya.chopra@veridian-corp.example",   date: "2026-09-25", text: "Requesting approval to install a browser extension for productivity tracking.", status: "Not started" },
    { id: "REQ-15", name: "Rahul Menon",    email: "rahul.menon@veridian-corp.example",    date: "2026-09-25", text: "hey can you help, its not working", status: "Not started" }
  ],

  tickets: [
    { id: "TK-1042", name: "R. Verma",     summary: "VPN credential expired",            status: "Resolved (closed)",                                   closed: true,  intent: "vpn" },
    { id: "TK-1043", name: "S. Iyer",      summary: "Laptop replacement (3.2 yrs old)",  status: "Approved — pending fulfillment (active)",            closed: false, intent: "laptop" },
    { id: "TK-1044", name: "A. Khan",      summary: "Non-catalog software request",      status: "Pending Security review (active)",                   closed: false, intent: "software" },
    { id: "TK-1045", name: "P. Joshi",     summary: "Mailbox quota increase",            status: "Approved at 35GB (closed)",                          closed: true,  intent: "mailbox" },
    { id: "TK-1046", name: "M. Das",       summary: "Printer paper jam, floor 2",        status: "Resolved (closed)",                                   closed: true,  intent: "printer" },
    { id: "TK-1047", name: "K. Singh",     summary: "Home office equipment request",     status: "Pending Finance (active)",                            closed: false, intent: "wfh" },
    { id: "TK-1048", name: "T. Rao",       summary: "Phishing email reported",           status: "Escalated to Security — under investigation (active)", closed: false, intent: "security" },
    { id: "TK-1049", name: "V. Nambiar",   summary: "Password reset",                    status: "Resolved (closed)",                                   closed: true,  intent: "password" },
    { id: "TK-1050", name: "J. Fernandes", summary: "Admin access request",              status: "Rejected — no business justification provided (closed)", closed: true, intent: "privileged" },
    { id: "TK-1051", name: "L. Menon",     summary: "Guest Wi-Fi issued",                status: "Resolved (closed)",                                   closed: true,  intent: "guestwifi" }
  ]
};
